### ISSUE TITLE
Undeclared dependency on XML::DOM

### ISSUE THREAD

**Issue by andk** [rizen/USPS-RateRequest#1]
As per subject. Grep:

http://search.cpan.org/grep?release=USPS-RateRequest-0.0100;string=XML::DOM;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/45392786

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by perlDreamer** [comment]
The actual dependency is on XML::Simple, and this commit 352ccea adds that to the dist.ini file for the project.  I'll close this ticket when the new version is released.

**Comment by andk** [comment]
It seems that it still (or again) is dependeing on XML::DOM. This is a grep http://search.cpan.org/grep?release=USPS-RateRequest-1.0001;string=XML::DOM;n=1;C=0

This is the found line: https://metacpan.org/source/RIZEN/USPS-RateRequest-1.0001/lib/USPS/RateRequest.pm#L5

This is a fail report that explicitly complains about missing XML::DOM: http://www.cpantesters.org/cpan/report/56185687

**Comment by eserte** [comment]
Version 1.0002 also has the problem. See:
- http://analysis.cpantesters.org/solved?distv=USPS-RateRequest-1.0002
- http://matrix.cpantesters.org/?dist=USPS-RateRequest%201.0002

**Comment by eserte** [comment]
Same issue with USPS-RateRequest-1.0003

**Comment by rizen** [comment]
Very much correct. Fixed in 1.0004
